version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/djangoapp
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
