version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/djangoapp
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean_appdir.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/run_migrations.sh      # <--- Run migrations after code is copied
      timeout: 300
      runas: ec2-user
    
    - location: scripts/deploy.sh              # <--- Then deploy/start Gunicorn/Nginx
      timeout: 300
      runas: ec2-user
