version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/djangoapp
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/clean_appdir.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
