version: 0.2

env:
  variables:
    GITHUB_REPO: "github.com/GhassenRabii/Productivity"
  # In CodeBuild console:
  #   - GITHUB_TOKEN: your PAT with repo:contents (or repo) scope


phases:
  install:
    commands:
      - echo "Installing dependencies…"
      - pip install --upgrade pip
      - cd $CODEBUILD_SRC_DIR
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Initializing Git in source directory…"
      - cd $CODEBUILD_SRC_DIR
      # Turn the unzipped source into a git repo
      - git init
      - git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_REPO}"
      - git fetch origin main
      - git reset --hard origin/main
      - echo "Git initialized; ready to detect migrations"

  build:
    commands:
      - echo "Generating migrations…"
      - cd $CODEBUILD_SRC_DIR
      - python manage.py makemigrations --noinput
      - |
        NEW=$(git diff --name-only origin/main HEAD -- tasks/migrations)
        if [ -n "$NEW" ]; then
          echo "🛠 New migrations detected:"
          echo "$NEW"
          git config user.email "ci-bot@yourdomain.com"
          git config user.name  "CI Bot"
          git add tasks/migrations
          git commit -m "ci: auto-generate migrations [skip ci]"
          echo "Pushing migrations to GitHub…"
          git push origin HEAD:main || { echo "❌ git push failed"; exit 1; }
        else
          echo "✅ No new migrations."
        fi

artifacts:
  files:
    - '**/*'
  files:
    - '**/*'
