version: 0.2

env:
  variables:
    # If you need any Django env vars for settings, add them here.
    # DJANGO_SETTINGS_MODULE: "mysite.settings"
    # You do NOT need DB creds just to check migrations.
    PIP_NO_CACHE_DIR: "1"

phases:
  install:
    commands:
      - echo "Installing dependencies…"
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Verifying that migrations are committed (no generation in CI)…"
      # This exits non-zero if Django detects model changes that would create a migration.
      - python manage.py makemigrations --check --dry-run
      - echo "✅ Migrations are up to date."
      # Optional: quick sanity check
      - python manage.py showmigrations tasks || true

  build:
    commands:
      # Optional: run tests; if you use DB, point tests to sqlite or a test DB
      # - python manage.py test -q
      - echo "Build phase complete."

artifacts:
  files:
    - '**/*'
  discard-paths: no
  exclude-paths:
    - '.git/**'
    - 'venv/**'
    - '**/__pycache__/**'
    - '.pytest_cache/**'
