version: 0.2

env:
  variables:
    GITHUB_REPO: "github.com/GhassenRabii/Productivity"
  # In CodeBuild console:
  #   - GITHUB_TOKEN: your PAT with repo:contents (or repo) scope

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Configuring authenticated Git remote…"
      - git remote remove origin || true
      - git remote add origin "https://${GITHUB_TOKEN}@${GITHUB_REPO}"
      - git fetch origin main

  pre_build:
    commands:
      - echo "Configuring Git remote for authenticated pushes…"
      - git remote set-url origin "https://${GITHUB_TOKEN}@${GITHUB_REPO}"
      - git fetch origin main

  build:
    commands:
      - echo "Generating migrations…"
      - python manage.py makemigrations --noinput

      - echo "Detecting newly created migrations…"
      - |
        NEW=$(git diff --name-only origin/main HEAD -- tasks/migrations)
        if [ -n "$NEW" ]; then
          echo "🛠 New migrations detected:"
          echo "$NEW"
          git config user.email "ci-bot@yourdomain.com"
          git config user.name "CI Bot"
          git add tasks/migrations
          git commit -m "ci: auto-generate migrations [skip ci]"
          echo "Pushing migrations to GitHub…"
          if ! git push origin HEAD:main; then
            echo "❌ ERROR: git push failed"
            exit 1
          fi
        else
          echo "✅ No new migrations."
        fi

artifacts:
  files:
    - '**/*'
