# Generated by Django 4.2.10 on 2025-09-05 11:10
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_add_groups_to_models'),
    ]
    operations = [
        migrations.AddField(
            model_name='habit',
            name='tags',
            field=models.CharField(
                blank=True,
                help_text='Comma-separated tags, e.g. Ideas, Work',
                max_length=100,
            ),
        ),
    ]
